### ISSUE TITLE
CAD file of the franka_panda

### ISSUE THREAD

**Issue by Nash-dc** [HoangGiang93/mujoco_robots#2]
Hi Mr.Hoang,

I'm interested in knowing whether you have the CAD file or SolidWorks file for either the [dual_panda](https://github.com/HoangGiang93/mujoco_robots/blob/main/franka/franka_description/robots/dual_panda_arm.urdf.xacro) or the [panda-arm](https://github.com/HoangGiang93/mujoco_robots/blob_main/franka/franka_description/robots/panda_arm.urdf.xacro).
As I am looking to modify the base's orientation, having access to a CAD file would greatly facilitate the process. I appreciate your assistance in this matter!

**Comment by HoangGiang93** [comment]
Just use Blender, it's lightweight, open source and supports every format. I don't have any CAD or Solidwork files

**Comment by Nash-dc** [comment]
Thank you!
